// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmBNfpvaA_xYGg5_OCMzBsANVkz0wveDY',
    appId: '1:465937542794:web:abe5612426bbcc3337c773',
    messagingSenderId: '465937542794',
    projectId: 'sabai-bc67f',
    authDomain: 'sabai-bc67f.firebaseapp.com',
    storageBucket: 'sabai-bc67f.appspot.com',
    measurementId: 'G-PZBPSGP0WD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgrdBPLekGt3qjxyWScNltkISbiad1LQ4',
    appId: '1:465937542794:android:4ad24306e624e13037c773',
    messagingSenderId: '465937542794',
    projectId: 'sabai-bc67f',
    storageBucket: 'sabai-bc67f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbQ9ZUn_v-bI1gQnY0ro2GV0uiVF_6gvY',
    appId: '1:465937542794:ios:6f466e590a349b7137c773',
    messagingSenderId: '465937542794',
    projectId: 'sabai-bc67f',
    storageBucket: 'sabai-bc67f.appspot.com',
    iosBundleId: 'com.example.sabai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbQ9ZUn_v-bI1gQnY0ro2GV0uiVF_6gvY',
    appId: '1:465937542794:ios:4760f346d708c41337c773',
    messagingSenderId: '465937542794',
    projectId: 'sabai-bc67f',
    storageBucket: 'sabai-bc67f.appspot.com',
    iosBundleId: 'com.example.sabai.RunnerTests',
  );
}
